<div class="gallery">
    <a href="assets/images/gallery/taverna-de-la-sal-00.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-00.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-01.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-01.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-02.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-02.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-03.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-03.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>          
    <a href="assets/images/gallery/taverna-de-la-sal-04.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-04.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-05.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-05.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-06.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-06.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-07.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-07.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-08.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-08.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-09.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-09.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-10.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-10.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-11.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-11.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-12.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-12.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-13.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-13.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-14.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-14.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-15.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-15.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-16.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-16.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-17.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-17.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-18.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-18.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-19.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-19.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-20.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-20.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-21.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-21.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-22.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-22.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-23.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-23.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-24.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-24.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-25.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-25.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-26.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-26.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    <a href="assets/images/gallery/taverna-de-la-sal-27.jpg" class="swipebox thumbnail"><img class="th-image" src="assets/images/gallery/th_taverna-de-la-sal-27.jpg" width="300" height="300" alt="Taverna de la Sal - L'Escala"></a>
    
</div>